---
title: "Data Science for Public Policy"
subtitle: "Assignment 04"
author: "Ruiyang Zhang - rz326; Xiangming Zeng - xz634; Xiaorui Shi - xs215"
execute:
  warning: false
format:
  html:
    embed-resources: true
---

## Source of Data

*??*

## Libraries

```{r}
library(tidyverse)
library(haven)
```

## Data preparation

```{r}
qog <- read_dta("data/idm_qog.dta")
qog <- qog %>% 
  select(year, 
         country_name = cname, 
         gdp_per_capita = gle_cgdpc, 
         democracy = chga_demo, 
         transparency_index = diat_ti, 
         new_busi_density = wdi_busden,
         level_of_democracy = ht_ipolity2
         ) 
```

## Exercise 03

The message says "The following paths are ignored by one of your .gitignore files: data"

## Exercise 04; graph 1

```{r}
qog %>% 
  filter(year==2008) %>% 
  ggplot(aes(gdp_per_capita)) +
  geom_histogram(bins = 80,fill="deepskyblue3",alpha=0.7)+
  labs(
    title = "Distribution of countries' GDP per capita",
    subtitle = "US Dollar($)",
    y = "Frequency",
    x = "GDP per capita",
    caption = "Source: The Quality of Government Basic Dataset (2023)"
  )

```


```{r}
qog %>% 
  filter(year==2008) %>% 
  mutate(chrdemo = case_when(
    democracy==0 ~ "Dictatorship",
    democracy==1 ~ "Democracy")) %>%
  filter(chrdemo!=is.na(chrdemo)) %>% 
  ggplot(aes(chrdemo,gdp_per_capita))+
  geom_boxplot(aes(fill=chrdemo))+
  labs(
    title = "GDP per capita by regime types",
    subtitle = "US Dollar($)",
    y = "GDP per capita",
    caption = "Source: The Quality of Government Basic Dataset (2023)"
  )

```


```{r}
qog %>% ggplot(aes(x = transparency_index, y = new_busi_density))+
  geom_point(aes(color = level_of_democracy, size = gdp_per_capita),
             ) +
  geom_smooth(method = "lm") +
  scale_y_log10() +
  xlab("Transparency index") +
  ylab("New business density") +
  labs(title = "The Relationship Between Transparancy and Entrepreneurship",
       subtitle = "Can information transparancy enhance business growth?",
       caption = "Data Source: The Quality of Government Basic Dataset (2023)") +
  labs(color = "Level of democracy", size = "GDP per Capita") +
  theme(
    legend.key = element_blank(),
    legend.key.size = unit(0.45, "cm")
  )

```


